# Generated by Django 4.0.1 on 2022-01-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0002_alter_place_enemy'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('satiety', models.IntegerField()),
                ('section', models.CharField(default='Food', max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='armor',
            name='section',
            field=models.CharField(default='Armor', max_length=30),
        ),
        migrations.AddField(
            model_name='weapon',
            name='section',
            field=models.CharField(default='Weapon', max_length=30),
        ),
    ]
