# Generated by Django 4.0.1 on 2022-02-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0003_food_armor_section_weapon_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_rest_place',
            field=models.BooleanField(default=True),
        ),
    ]
