# Generated by Django 4.0.1 on 2022-02-04 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0004_place_is_rest_place'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='seal',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='place',
            name='first_enter_text',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='place',
            name='is_first_enter',
            field=models.BooleanField(default=True),
        ),
    ]
