# Generated by Django 4.0.1 on 2022-02-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0006_hint'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='not_allowed_direction',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
