# Generated by Django 4.0.1 on 2022-02-12 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0007_place_not_allowed_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
