# Generated by Django 4.0.1 on 2022-02-13 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0008_enemy_exp'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='level',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='weapon',
            name='level',
            field=models.IntegerField(default=1),
        ),
    ]
