# Generated by Django 4.0.1 on 2022-02-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0009_armor_level_weapon_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='death_message',
            field=models.TextField(null=True),
        ),
    ]
