# Generated by Django 4.0.2 on 2022-02-19 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0010_enemy_death_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='is_enter_for_sublock',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='place',
            name='subloc_pk',
            field=models.IntegerField(default=0),
        ),
    ]
