# Generated by Django 4.0.2 on 2022-02-19 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0011_place_is_enter_for_sublock_place_subloc_pk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='is_enter_for_sublock',
            new_name='is_enter_for_subloc',
        ),
    ]
