# Generated by Django 4.0.1 on 2022-02-19 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0012_alter_armor_part'),
    ]

    operations = [
        migrations.AddField(
            model_name='armor',
            name='dexterity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='weapon',
            name='crit_add',
            field=models.IntegerField(default=0),
        ),
    ]
