# Generated by Django 4.0.2 on 2022-02-19 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Game', '0012_rename_is_enter_for_sublock_place_is_enter_for_subloc'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='is_enter_for_subloc',
            new_name='transition',
        ),
    ]
